from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from src import res_rc
import sys

mainIcon = 'src/icon.ico'
popUpIcon = 'src/icon.ico'
selectedEmotion =''
descContent = ''
ad1Content = ''
ad2Content = ''
ad3Content = ''
ad4Content = ''

def main():
    def angry():
        global selectedEmotion, descContent, ad1Content, ad2Content, ad3Content, ad4Content, popUpIcon
        popUpIcon = 'src/angry.ico'
        selectedEmotion = 'Angry'
        descContent = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris et consequat arcu. In hac habitasse platea dictumst. Nulla auctor condimentum laoreet.'
        ad1Content = 'Lorem Ipsum is smart dummy text.'
        ad2Content = 'Lorem Ipsum is smart dummy text.'
        ad3Content = 'Lorem Ipsum is smart dummy text.'
        ad4Content = 'Lorem Ipsum is smart dummy text.'

    def anxious():
        global selectedEmotion, descContent, ad1Content, ad2Content, ad3Content, ad4Content, popUpIcon
        popUpIcon = 'src/anxious.ico'
        selectedEmotion = 'Anxious'
        descContent = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris et consequat arcu. In hac habitasse platea dictumst. Nulla auctor condimentum laoreet.'
        ad1Content = 'Lorem Ipsum is smart dummy text.'
        ad2Content = 'Lorem Ipsum is smart dummy text.'
        ad3Content = 'Lorem Ipsum is smart dummy text.'
        ad4Content = 'Lorem Ipsum is smart dummy text.'

    def disgusted():
        global selectedEmotion, descContent, ad1Content, ad2Content, ad3Content, ad4Content, popUpIcon
        popUpIcon = 'src/disgusted.ico'
        selectedEmotion = 'Disgusted'
        descContent = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris et consequat arcu. In hac habitasse platea dictumst. Nulla auctor condimentum laoreet.'
        ad1Content = 'Lorem Ipsum is smart dummy text.'
        ad2Content = 'Lorem Ipsum is smart dummy text.'
        ad3Content = 'Lorem Ipsum is smart dummy text.'
        ad4Content = 'Lorem Ipsum is smart dummy text.'

    def happy():
        global selectedEmotion, descContent, ad1Content, ad2Content, ad3Content, ad4Content, popUpIcon
        popUpIcon = 'src/happy.ico'
        selectedEmotion = 'Happy'
        descContent = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris et consequat arcu. In hac habitasse platea dictumst. Nulla auctor condimentum laoreet.'
        ad1Content = 'Lorem Ipsum is smart dummy text.'
        ad2Content = 'Lorem Ipsum is smart dummy text.'
        ad3Content = 'Lorem Ipsum is smart dummy text.'
        ad4Content = 'Lorem Ipsum is smart dummy text.'

    def sad():
        global selectedEmotion, descContent, ad1Content, ad2Content, ad3Content, ad4Content, popUpIcon
        popUpIcon = 'src/sad.ico'
        selectedEmotion = 'Sad'
        descContent = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris et consequat arcu. In hac habitasse platea dictumst. Nulla auctor condimentum laoreet.'
        ad1Content = 'Lorem Ipsum is smart dummy text.'
        ad2Content = 'Lorem Ipsum is smart dummy text.'
        ad3Content = 'Lorem Ipsum is smart dummy text.'
        ad4Content = 'Lorem Ipsum is smart dummy text.'

    def surprised():
        global selectedEmotion, descContent, ad1Content, ad2Content, ad3Content, ad4Content, popUpIcon
        popUpIcon = 'src/surprised.ico'
        selectedEmotion = 'Surprised'
        descContent = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris et consequat arcu. In hac habitasse platea dictumst. Nulla auctor condimentum laoreet.'
        ad1Content = 'Lorem Ipsum is smart dummy text.'
        ad2Content = 'Lorem Ipsum is smart dummy text.'
        ad3Content = 'Lorem Ipsum is smart dummy text.'
        ad4Content = 'Lorem Ipsum is smart dummy text.'

    

    class Ui_Form(object):
        def setupUi(self, Form):
            Form.setObjectName("Form")
            Form.resize(480, 640)
            palette = QtGui.QPalette()
            brush = QtGui.QBrush(QtGui.QColor(255, 241, 231))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
            brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
            brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
            brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
            brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
            brush = QtGui.QBrush(QtGui.QColor(176, 176, 176))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(229, 83, 45))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
            brush = QtGui.QBrush(QtGui.QColor(216, 216, 216))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27, 128))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 241, 231))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
            brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
            brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
            brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
            brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
            brush = QtGui.QBrush(QtGui.QColor(176, 176, 176))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(229, 83, 45))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
            brush = QtGui.QBrush(QtGui.QColor(216, 216, 216))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27, 128))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
            brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
            brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
            brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
            brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
            brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
            brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
            brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
            brush = QtGui.QBrush(QtGui.QColor(229, 83, 45))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(229, 83, 45))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
            brush = QtGui.QBrush(QtGui.QColor(216, 216, 216))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
            Form.setPalette(palette)
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap(popUpIcon), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            Form.setWindowIcon(icon)
            self.emotion = QtWidgets.QLabel(Form)
            self.emotion.setGeometry(QtCore.QRect(20, 20, 321, 71))
            self.textBrowser = QtWidgets.QTextBrowser(self.emotion)
            self.textBrowser.setEnabled(False)
            self.textBrowser.setGeometry(QtCore.QRect(-30, 430, 311, 261))
            self.textBrowser.setAutoFillBackground(False)
            self.textBrowser.setObjectName("textBrowser")
            self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
            QFontDatabase.addApplicationFont('src/RopaSoftPTT-ExtraBold.ttf')
            font = QtGui.QFont()
            font.setFamily("Ropa Soft PTT ExtraBold")
            font.setPointSize(24)
            self.emotion.setFont(font)
            self.emotion.setObjectName("emotion")
            self.desc = QtWidgets.QLabel(Form)
            self.desc.setGeometry(QtCore.QRect(50, 90, 381, 151))
            font.setPointSize(15)
            self.desc.setFont(font)
            self.desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
            self.desc.setWordWrap(True)
            self.desc.setObjectName("desc")
            self.advice_label = QtWidgets.QLabel(Form)
            self.advice_label.setGeometry(QtCore.QRect(20, 270, 321, 71))
            font.setPointSize(24)
            self.advice_label.setFont(font)
            self.advice_label.setObjectName("advice_label")
            self.ad1 = QtWidgets.QLabel(Form)
            self.ad1.setGeometry(QtCore.QRect(50, 350, 381, 31))
            font.setPointSize(15)
            self.ad1.setFont(font)
            self.ad1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
            self.ad1.setWordWrap(True)
            self.ad1.setObjectName("ad1")
            self.ad2 = QtWidgets.QLabel(Form)
            self.ad2.setGeometry(QtCore.QRect(50, 390, 381, 31))
            font.setPointSize(15)
            self.ad2.setFont(font)
            self.ad2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
            self.ad2.setWordWrap(True)
            self.ad2.setObjectName("ad2")
            self.ad3 = QtWidgets.QLabel(Form)
            self.ad3.setGeometry(QtCore.QRect(50, 430, 381, 31))
            font.setPointSize(15)
            self.ad3.setFont(font)
            self.ad3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
            self.ad3.setWordWrap(True)
            self.ad3.setObjectName("ad3")
            self.ad4 = QtWidgets.QLabel(Form)
            self.ad4.setGeometry(QtCore.QRect(50, 470, 381, 31))
            font.setPointSize(15)
            self.ad4.setFont(font)
            self.ad4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
            self.ad4.setWordWrap(True)
            self.ad4.setObjectName("ad4")

            self.retranslateUi(Form)
            QtCore.QMetaObject.connectSlotsByName(Form)

        def retranslateUi(self, Form):
            _translate = QtCore.QCoreApplication.translate
            Form.setWindowTitle(_translate("Form", "You are " + selectedEmotion))
            self.emotion.setText(_translate("Form", "You are " + selectedEmotion))
            self.desc.setText(_translate("Form", descContent))
            self.advice_label.setText(_translate("Form", "Pieces of advice:"))
            self.ad1.setText(_translate("Form", ad1Content))
            self.ad2.setText(_translate("Form", ad2Content))
            self.ad3.setText(_translate("Form", ad3Content))
            self.ad4.setText(_translate("Form", ad4Content))

    class Ui_MainWindow(object):
        def openPopUp(self, emotion):
            if emotion == 'angry':
                angry()
            elif emotion == 'anxious':
                anxious()
            elif emotion == 'disgusted':
                disgusted()
            elif emotion == 'happy':
                happy()
            elif emotion == 'sad':
                sad()
            elif emotion == 'surprised':
                surprised()
            self.Form = QtWidgets.QWidget()
            self.ui = Ui_Form()
            self.ui.setupUi(self.Form)
            self.Form.show()

        def setupUi(self, MainWindow):
            MainWindow.setObjectName("#EmotionCheck")
            MainWindow.resize(469, 610)
            MainWindow.setMinimumSize(QtCore.QSize(80, 50))
            palette = QtGui.QPalette()
            brush = QtGui.QBrush(QtGui.QColor(255, 241, 231))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
            brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
            brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
            brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
            brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
            brush = QtGui.QBrush(QtGui.QColor(176, 176, 176))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(229, 83, 45))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
            brush = QtGui.QBrush(QtGui.QColor(216, 216, 216))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27, 128))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 241, 231))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
            brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
            brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
            brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
            brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
            brush = QtGui.QBrush(QtGui.QColor(176, 176, 176))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(229, 83, 45))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
            brush = QtGui.QBrush(QtGui.QColor(216, 216, 216))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27, 128))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
            brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
            brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
            brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
            brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
            brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
            brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
            brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
            brush = QtGui.QBrush(QtGui.QColor(229, 83, 45))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(229, 83, 45))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
            brush = QtGui.QBrush(QtGui.QColor(30, 28, 27))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
            brush = QtGui.QBrush(QtGui.QColor(216, 216, 216))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
            MainWindow.setPalette(palette)
            # trayIcon = QIcon('src/icon.ico')
            # tray = QSystemTrayIcon()
            # tray.setIcon(trayIcon)
            # tray.setVisible(True)
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap(mainIcon), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            MainWindow.setWindowIcon(icon)
            QFontDatabase.addApplicationFont('src/RopaSoftPTT-ExtraBold.ttf')
            font = QtGui.QFont()
            font.setFamily("Ropa Soft PTT ExtraBold")
            MainWindow.setFont(font)
            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
            self.textBrowser.setEnabled(False)
            self.textBrowser.setGeometry(QtCore.QRect(-30, 430, 311, 261))
            self.textBrowser.setAutoFillBackground(False)
            self.textBrowser.setObjectName("textBrowser")
            self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
            self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
            self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 140, 341, 441))
            self.gridLayoutWidget.setObjectName("gridLayoutWidget")
            self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
            self.gridLayout.setContentsMargins(0, 0, 0, 0)
            self.gridLayout.setObjectName("gridLayout")
            self.Anxious = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.openPopUp('anxious'))
            self.Anxious.setMinimumSize(QtCore.QSize(80, 50))
            font = QtGui.QFont()
            font.setFamily("Ropa Soft PTT ExtraBold")
            font.setPointSize(12)
            self.Anxious.setFont(font)
            self.Anxious.setObjectName("Anxious")
            self.gridLayout.addWidget(self.Anxious, 1, 0, 1, 1)
            self.Happy = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.openPopUp('happy'))
            self.Happy.setMinimumSize(QtCore.QSize(80, 50))
            self.Happy.setFont(font)
            self.Happy.setObjectName("Happy")
            self.gridLayout.addWidget(self.Happy, 5, 0, 1, 1)
            self.Angry = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.openPopUp('angry'))
            self.Angry.setMinimumSize(QtCore.QSize(80, 50))
            self.Angry.setFont(font)
            self.Angry.setObjectName("Angry")
            self.gridLayout.addWidget(self.Angry, 0, 0, 1, 1)
            self.Disgusted = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.openPopUp('disgusted'))
            self.Disgusted.setMinimumSize(QtCore.QSize(80, 50))
            self.Disgusted.setFont(font)
            self.Disgusted.setObjectName("Disgusted")
            self.gridLayout.addWidget(self.Disgusted, 2, 0, 1, 1)
            self.Surprised = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.openPopUp('surprised'))
            self.Surprised.setMinimumSize(QtCore.QSize(80, 50))
            font.setBold(True)
            font.setWeight(75)
            self.Surprised.setFont(font)
            self.Surprised.setObjectName("Surprised")
            self.gridLayout.addWidget(self.Surprised, 7, 0, 1, 1)
            self.Sad = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.openPopUp('sad'))
            self.Sad.setMinimumSize(QtCore.QSize(80, 50))
            self.Sad.setFont(font)
            self.Sad.setObjectName("Sad")
            self.gridLayout.addWidget(self.Sad, 6, 0, 1, 1)
            self.label = QtWidgets.QLabel(self.centralwidget)
            self.label.setGeometry(QtCore.QRect(80, 30, 301, 50))
            self.label.setMinimumSize(QtCore.QSize(80, 100))
            font = QtGui.QFont()
            font.setFamily("Ropa Soft PTT ExtraBold")
            font.setBold(True)
            font.setWeight(75)
            self.label.setFont(font)
            self.label.setAlignment(QtCore.Qt.AlignCenter)
            self.label.setObjectName("label")
            self.label.setWordWrap(True)
            MainWindow.setCentralWidget(self.centralwidget)
            self.statusbar = QtWidgets.QStatusBar(MainWindow)
            self.statusbar.setObjectName("statusbar")
            MainWindow.setStatusBar(self.statusbar)

            self.retranslateUi(MainWindow)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("#EmotionCheck", "#EmotionCheck"))
            self.Anxious.setText(_translate("#EmotionCheck", "ANXIOUS"))
            self.Happy.setText(_translate("#EmotionCheck", "HAPPY"))
            self.Angry.setText(_translate("#EmotionCheck", "ANGRY"))
            self.Disgusted.setText(_translate("#EmotionCheck", "DISGUSTED"))
            self.Surprised.setText(_translate("#EmotionCheck", "SURPRISED"))
            self.Sad.setText(_translate("#EmotionCheck", "SAD"))
            self.label.setText(_translate("#EmotionCheck", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">HOW ARE YOU FEELING?</span></p></body></html>"))
            self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ropa Soft PTT ExtraBold\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/tone/tone.png\" /></p></body></html>"))

    if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())

main()